import { PropertyType } from "@/components/Property";

const properties: PropertyType[] = [
  {
    id: "1",
    name: "Luxury Apartment in Lagos",
    yearBuilt: "2020",
    garageSpace: 2,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, cumque aut molestiae minus nisi iste quasi, error culpa nihil doloremque suscipit quidem sunt earum voluptatem labore nesciunt laborum harum sit!",
    images: ["/property-1.jpg", "/property-1.jpg", "/property-1.jpg"],
    price: 50000000,
    location: {
      city: "Lagos",
      state: "Lagos",
    },
    type: "Apartment",
    agent: {
      id: "1",
      firstname: "Chidi",
      lastname: "Okeke",
      bio: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, eos. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, eos.",
      imageUrl: "/profile-pic.jpg",
      companyName: "Treasure Estate",
      phoneNumber: "+2341234567890",
      workEmail: "chidi.okeke@gmail.com",
      facebook: "@chidiokeke",
      twitter: "@chidiokeke",
      linkedIn: "@chidiokeke",
      instagram: "@chidiokeke",
    },
    views: 10,
    beds: 3,
    bath: 2,
    area: 150,
    isRent: false,
    petsAllowed: true,
    dateCreated: "2024-06-25T16:34:11.031Z",
    isPublished: true,
  },
  {
    id: "2",
    name: "Spacious House in Abuja",
    yearBuilt: "2020",
    garageSpace: 2,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, cumque aut molestiae minus nisi iste quasi, error culpa nihil doloremque suscipit quidem sunt earum voluptatem labore nesciunt laborum harum sit!",
    images: ["/property-2.jpg", "/property-2.jpg", "/property-2.jpg"],
    price: 150000,
    location: {
      city: "Abuja",
      state: "FCT",
    },
    type: "House",
    agent: {
      id: "1",
      firstname: "Chidi",
      lastname: "Okeke",
      bio: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, eos. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, eos.",
      imageUrl: "/profile-pic.jpg",
      companyName: "Treasure Estate",
      phoneNumber: "+2341234567890",
      workEmail: "chidi.okeke@gmail.com",
      facebook: "@chidiokeke",
      twitter: "@chidiokeke",
      linkedIn: "@chidiokeke",
      instagram: "@chidiokeke",
    },
    views: 10,
    beds: 4,
    bath: 3,
    area: 300,
    isRent: true,
    petsAllowed: false,
    dateCreated: "2024-06-24T16:34:11.031Z",
    isPublished: true,
  },
  {
    id: "3",
    name: "Elegant Duplex in Port Harcourt",
    yearBuilt: "2020",
    garageSpace: 2,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, cumque aut molestiae minus nisi iste quasi, error culpa nihil doloremque suscipit quidem sunt earum voluptatem labore nesciunt laborum harum sit!",
    images: ["/property-3.jpg", "/property-3.jpg", "/property-3.jpg"],
    price: 35000000,
    location: {
      city: "Port Harcourt",
      state: "Rivers",
    },
    type: "Duplex",
    agent: {
      id: "1",
      firstname: "Chidi",
      lastname: "Okeke",
      bio: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, eos. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, eos.",
      imageUrl: "/profile-pic.jpg",
      companyName: "Treasure Estate",
      phoneNumber: "+2341234567890",
      workEmail: "chidi.okeke@gmail.com",
      facebook: "@chidiokeke",
      twitter: "@chidiokeke",
      linkedIn: "@chidiokeke",
      instagram: "@chidiokeke",
    },
    views: 10,
    beds: 5,
    bath: 4,
    area: 400,
    isRent: false,
    petsAllowed: true,
    dateCreated: "2024-06-23T16:34:11.031Z",
    isPublished: true,
  },
  {
    id: "4",
    name: "Modern Apartment in Kano",
    yearBuilt: "2020",
    garageSpace: 2,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, cumque aut molestiae minus nisi iste quasi, error culpa nihil doloremque suscipit quidem sunt earum voluptatem labore nesciunt laborum harum sit!",
    images: ["/property-4.jpg", "/property-4.jpg", "/property-4.jpg"],
    price: 100000,
    location: {
      city: "Kano",
      state: "Kano",
    },
    type: "Apartment",
    agent: {
      id: "1",
      firstname: "Chidi",
      lastname: "Okeke",
      bio: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, eos. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, eos.",
      imageUrl: "/profile-pic.jpg",
      companyName: "Treasure Estate",
      phoneNumber: "+2341234567890",
      workEmail: "chidi.okeke@gmail.com",
      facebook: "@chidiokeke",
      twitter: "@chidiokeke",
      linkedIn: "@chidiokeke",
      instagram: "@chidiokeke",
    },
    views: 10,
    beds: 2,
    bath: 1,
    area: 120,
    isRent: true,
    petsAllowed: false,
    dateCreated: "2024-06-22T16:34:11.031Z",
    isPublished: true,
  },
  {
    id: "5",
    name: "Family House in Ibadan",
    yearBuilt: "2020",
    garageSpace: 2,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, cumque aut molestiae minus nisi iste quasi, error culpa nihil doloremque suscipit quidem sunt earum voluptatem labore nesciunt laborum harum sit!",
    images: ["/property-5.jpg", "/property-5.jpg", "/property-5.jpg"],
    price: 45000000,
    location: {
      city: "Ibadan",
      state: "Oyo",
    },
    type: "House",
    agent: {
      id: "1",
      firstname: "Chidi",
      lastname: "Okeke",
      bio: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, eos. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, eos.",
      imageUrl: "/profile-pic.jpg",
      companyName: "Treasure Estate",
      phoneNumber: "+2341234567890",
      workEmail: "chidi.okeke@gmail.com",
      facebook: "@chidiokeke",
      twitter: "@chidiokeke",
      linkedIn: "@chidiokeke",
      instagram: "@chidiokeke",
    },
    views: 10,
    beds: 4,
    bath: 3,
    area: 350,
    isRent: false,
    petsAllowed: false,
    dateCreated: "2024-06-21T16:34:11.031Z",
    isPublished: true,
  },
  {
    id: "6",
    name: "Cozy Studio in Enugu",
    yearBuilt: "2020",
    garageSpace: 2,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, cumque aut molestiae minus nisi iste quasi, error culpa nihil doloremque suscipit quidem sunt earum voluptatem labore nesciunt laborum harum sit!",
    images: ["/property-6.jpg", "/property-6.jpg", "/property-6.jpg"],
    price: 80000,
    location: {
      city: "Enugu",
      state: "Enugu",
    },
    type: "Studio",
    agent: {
      id: "1",
      firstname: "Chidi",
      lastname: "Okeke",
      bio: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, eos. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, eos.",
      imageUrl: "/profile-pic.jpg",
      companyName: "Treasure Estate",
      phoneNumber: "+2341234567890",
      workEmail: "chidi.okeke@gmail.com",
      facebook: "@chidiokeke",
      twitter: "@chidiokeke",
      linkedIn: "@chidiokeke",
      instagram: "@chidiokeke",
    },
    views: 10,
    beds: 1,
    bath: 1,
    area: 80,
    isRent: true,
    petsAllowed: false,
    dateCreated: "2024-06-20T16:34:11.031Z",
    isPublished: true,
  },
  {
    id: "7",
    name: "Charming Bungalow in Benin City",
    yearBuilt: "2020",
    garageSpace: 2,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, cumque aut molestiae minus nisi iste quasi, error culpa nihil doloremque suscipit quidem sunt earum voluptatem labore nesciunt laborum harum sit!",
    images: ["/property-7.jpg", "/property-7.jpg", "/property-7.jpg"],
    price: 25000000,
    location: {
      city: "Benin City",
      state: "Edo",
    },
    type: "House",
    agent: {
      id: "1",
      firstname: "Chidi",
      lastname: "Okeke",
      bio: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, eos. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, eos.",
      imageUrl: "/profile-pic.jpg",
      companyName: "Treasure Estate",
      phoneNumber: "+2341234567890",
      workEmail: "chidi.okeke@gmail.com",
      facebook: "@chidiokeke",
      twitter: "@chidiokeke",
      linkedIn: "@chidiokeke",
      instagram: "@chidiokeke",
    },
    views: 10,
    beds: 3,
    bath: 2,
    area: 200,
    isRent: false,
    petsAllowed: true,
    dateCreated: "2024-06-19T16:34:11.031Z",
    isPublished: true,
  },
  {
    id: "8",
    name: "Affordable Apartment in Kaduna",
    yearBuilt: "2020",
    garageSpace: 2,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, cumque aut molestiae minus nisi iste quasi, error culpa nihil doloremque suscipit quidem sunt earum voluptatem labore nesciunt laborum harum sit!",
    images: ["/property-8.jpg", "/property-8.jpg", "/property-8.jpg"],
    price: 200000,
    location: {
      city: "Kaduna",
      state: "Kaduna",
    },
    type: "Apartment",
    agent: {
      id: "1",
      firstname: "Chidi",
      lastname: "Okeke",
      bio: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, eos. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, eos.",
      imageUrl: "/profile-pic.jpg",
      companyName: "Treasure Estate",
      phoneNumber: "+2341234567890",
      workEmail: "chidi.okeke@gmail.com",
      facebook: "@chidiokeke",
      twitter: "@chidiokeke",
      linkedIn: "@chidiokeke",
      instagram: "@chidiokeke",
    },
    views: 10,
    beds: 2,
    bath: 2,
    area: 150,
    isRent: true,
    petsAllowed: true,
    dateCreated: "2024-06-18T16:34:11.031Z",
    isPublished: true,
  },
];

export async function getProperties() {
  return properties;
}

export async function getPropertiesByAgent(agentId: string) {
  return properties;
}

export async function getProperty(propertyId: string) {
  return properties.find((property) => property.id === propertyId);
}
